### ISSUE TITLE
License

### ISSUE THREAD

**Issue by chin123** [nti-Pi/AutoJudge#1]
Can you please specify the license for this program?
Thanks.

**Comment by nti-Pi** [comment]
Hi Chin. Could we further discuss this over chat?

**Comment by tsnl** [comment]
Hi Chin! Thanks for getting in touch with me!
I've gone ahead and added the MIT License to the project.

The project is currently undocumented, and has a large scope for expansion and improvement; for example, it currently requires a Bash shell, and doesn't support test-programs just yet.

We'd appreciate contributions to make the source more cross-platform (for example, by porting it to Python) and documenting its use.
